export { default as BaseButton } from "./BaseButton.vue";
export { default as BaseInput } from "./BaseInput.vue";
export { default as BaseHeader } from "./BaseHeader.vue";
export { default as BaseSidebar } from "./BaseSidebar.vue";
export { default as BaseTable } from "./BaseTable/index.vue";
export { default as BaseModal } from "./BaseModal.vue";
export { default as BaseSkelet } from "./BaseSkelet.vue";
export { default as BaseSpinner } from "./BaseSpinner.vue";
export { default as BaseFileInput } from "./BaseFileInput.vue";
